#ifndef _M_VER_
#define _M_VER_

/* Icon File */
#define VIconFileName "ICON1.ICO"

/* File Version Number */
#define VFileVersion "1.0"

/* Product Version Number */
#define VProductVersion "1.0"

/* Other Version Details */
#define VProductName "Installer"
#define VCompanyName "ODE"
#define VLegalCopyright "Copyright (c) 2001-Present Karthik Kumar Viswanathan"
#define VLegalTrademarks ""
#define VFileDescription "Installer - Extractor/Packer for DOS"
#define VComments ""
#define VInternalName "Installer"
#define VOriginalFilename "INSTALLR"

/* Language Details */
#define VCountry 0x409
#define VLanguage 1200

#endif /* _M_VER_ */
